#!/usr/bin/env python3
"""Generate docs/post-copy-recommendations.csv from drafted copy."""
from __future__ import annotations

import csv
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "docs" / "post-copy-recommendations.csv"

ROWS: list[dict[str, str]] = [
    {
        "slug": "apj-ministries",
        "title": "APJ Ministries - Album Release Website",
        "notes": "Current excerpt/body are identical and generic. Live site is Alicia Peters-Jordan Ministries (gospel recording artist): albums Redeemed and In High Praise, music player, galleries, shop, donate, booking. SEO is empty except an emulator localhost og:image — clear it so OG falls back to the main image. Source: apjministries.com.",
        "current_excerpt": "A wordpress site for a gospel recording artist",
        "recommended_excerpt": "A WordPress album site built to turn listeners into supporters — player, galleries, and shop.",
        "current_body": "<p>A wordpress site for a gospel recording artist</p>",
        "recommended_body": "<p>I designed and developed the album-release website for Alicia Peters-Jordan Ministries — a Richmond gospel artist whose work is built around worship, testimony, and service. The brief was not a brochure. It needed to sound like the music: inviting on first play, then deep enough to hold releases, photos, video, and a store.</p><p>I built the site in WordPress with a custom music player, image and video galleries, WooCommerce for albums such as <em>Redeemed</em> and <em>In High Praise</em>, and clear paths for booking, donations, and the ministry mission. Navigation, merchandising, and media are all tuned so a first-time visitor can listen, learn, and purchase without hunting through a generic church theme.</p><p>The result is a living catalog and campaign surface — not a one-page splash — that still looks considered on a phone in a sanctuary lobby.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "APJ Ministries — Gospel Album WordPress Site",
        "current_seo_description": "",
        "recommended_seo_description": "Alicia Peters-Jordan Ministries WordPress album site — music player, galleries, shop, and booking for a Richmond gospel artist.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "WordPress; gospel website; album release; music player; WooCommerce; Alicia Peters-Jordan",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "frendigo-app",
        "title": "Frendigo App",
        "notes": "Strongest existing body on the site — keep the product facts, rewrite in first person and lead with the marketplace thesis (no surge, subscription vs commissions). SEO title duplicates the post title; description copies the excerpt. Source: frendigo.com clients flow + resume (Senior Lead Developer).",
        "current_excerpt": "iOS, Android, and web transportation marketplace — cheap rides, great vibes.",
        "recommended_excerpt": "A three-platform ride marketplace built to replace surge with subscription pricing and direct pay.",
        "current_body": "<p>Multi-platform Frendigo app for riders and drivers: commute planner, provider marketplace with transparent estimates, mid-trip maps, itemized fares, and direct pay. Built as a Flutter mobile app with Angular web, Firebase, and Google Maps — subscription pricing from MPG, USDOT, and EIA gas data instead of per-trip commissions.</p>",
        "recommended_body": "<p>I am the senior lead developer on Frendigo, a three-platform transportation marketplace I architected so riders and drivers are not trapped in someone else’s surge math. Clients plan commutes, pick providers from a live marketplace, see itemized estimates before they book, and pay the provider directly. Providers set their own rates, vehicles, and add-ons — and keep more of what they earn.</p><p>I built the mobile clients in Flutter for iOS and Android, the web experience in Angular, and the realtime layer on Firebase with Google Maps for mid-trip tracking. Pricing is a subscription engine fed by MPG, USDOT, and EIA gas data rather than a per-trip commission. Reservations can be split across providers, modified after booking, and extended with backtrack when something is left behind.</p><p>The product is in TestFlight and Android beta: a full commute OS, not a skin on a rideshare clone.</p>",
        "current_seo_title": "Frendigo App",
        "recommended_seo_title": "Frendigo App — iOS, Android & Web Marketplace",
        "current_seo_description": "iOS, Android, and web transportation marketplace — cheap rides, great vibes.",
        "recommended_seo_description": "Frendigo transportation marketplace for iOS, Android, and web — transparent estimates, live maps, subscription pricing instead of surge.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Flutter; Angular; Firebase; Google Maps; transportation marketplace; commute app",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "frendigo-marketing-website",
        "title": "Frendigo Website",
        "notes": "Excerpt and body are placeholders. Live site is a dual-persona Angular marketing site (Clients vs Providers) with commute/earnings calculators and comparison storytelling. Source: frendigo.com.",
        "current_excerpt": "Custom Marketing Website",
        "recommended_excerpt": "A dual-persona marketing site designed to sell the switch — commute and earnings calculators, not a brochure.",
        "current_body": "<p>A public facing marketing website for Frendigo</p>",
        "recommended_body": "<p>I designed and built Frendigo.com as the public face of a product that has to explain itself in one screen: cheap rides, great vibes — then prove it. The site splits immediately into two journeys. Clients get a marketplace story, a commute estimator, and a side-by-side of Frendigo versus opaque surge platforms. Providers get earnings logic, rate control, and a reason to leave the middleman.</p><p>I developed it in Angular with custom illustration, motion, and HTML/CSS/JS — not a theme with a form slapped on. Interactive calculators, persona routing, and campaign-ready graphics do the conversion work that a static landing page cannot. Every module is built to travel: web, app store traffic, and future ops/training properties on the same stack.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Frendigo Marketing Website | Angular",
        "current_seo_description": "",
        "recommended_seo_description": "Frendigo.com marketing site in Angular — dual client/provider personas, commute and earnings calculators, custom graphics.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Angular; marketing website; interactive calculators; dual persona; custom graphics; Frendigo",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "genworth-r70-age-suit",
        "title": "Genworth — R70 Age Suit",
        "notes": "Body is already factual; rewrite in first person and name the campaign context (R70 age-simulation suit for long-term care education; Genworth #LetsTalk / Fortune 500 insurer). Do not claim you built the physical suit — you built the interactive web infographic and related AEM/LTC work. Sources: PR Newswire 2014, resume (Techead / Genworth 2014–15).",
        "current_excerpt": "Interactive R70 Age Suit infographic for genworth.com and the PRO Agent portal.",
        "recommended_excerpt": "An interactive Age Suit infographic built to let agents and families explore aging without the hardware.",
        "current_body": "<p>Custom AEM / JavaScript experience for Genworth Financial: an interactive R70 Age Suit infographic with hover targets for vision, hearing, arthritis, and muscle loss, plus help controls for showing, hiding, and explaining each hotspot.</p><p>Built while managing content for genworth.com and the PRO Agent portal on Adobe CQ5/AEM, including the Long Term Care responsive upgrade, Eloqua tagging, and SEO (Schema, OG meta, canonicals).</p>",
        "recommended_body": "<p>I built the interactive R70 Age Suit infographic for Genworth Financial — a Fortune 500 insurer using a first-of-its-kind age-simulation suit to push long-term care into the national conversation. The physical suit (vision loss, muffled hearing, restricted joints) needed a digital twin agents and families could explore without stepping into the hardware.</p><p>I developed a custom Adobe CQ5/AEM and JavaScript experience with front, side, and back views; hover hotspots for vision, hearing, arthritis, and muscle loss; and help controls to show, hide, and explain each target. It shipped on genworth.com and inside the PRO Agent portal — the same surfaces I was managing as senior content / front-end developer.</p><p>Alongside the infographic I led the Long Term Care site onto a fully responsive layout, tagged journeys for Eloqua, and implemented Schema, Open Graph, and canonicals so the campaign could be found and shared with the gravity it deserved.</p>",
        "current_seo_title": "Genworth — R70 Age Suit",
        "recommended_seo_title": "Genworth R70 Age Suit Infographic | AEM",
        "current_seo_description": "Interactive R70 Age Suit infographic for genworth.com and the PRO Agent portal.",
        "recommended_seo_description": "Interactive R70 Age Suit infographic for Genworth — hotspots, three views, AEM/JS, on genworth.com and the PRO Agent portal.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Adobe AEM; CQ5; interactive infographic; Genworth; long term care; JavaScript; Eloqua",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "industry-4-0",
        "title": "Industry 4.0",
        "notes": "Body undersells a feature-rich dashboard (map, realtime metrics, 3D floor plan, escalation). Frame as a production-monitoring showcase you designed and built. Live demo: react-industry4dot0-app.web.app. Do not invent a named factory client.",
        "current_excerpt": "A manufacturing facility monitoring dashboard",
        "recommended_excerpt": "A plant-floor dashboard designed to put live metrics, a 3D floor plan, and escalation in one view.",
        "current_body": "<p>Showcasing an industry 4.0 dashboard that monitors production lines, their outputs, and alerts when there are issues.</p>",
        "recommended_body": "<p>I designed and engineered this Industry 4.0 dashboard as a serious operations surface, not a chart gallery. The problem is familiar on a plant floor: production lives in one system, alarms in another, and the floor plan on a PDF someone printed in 2017. I collapsed that into a single React application.</p><p>Operators pick a facility on Google Maps, then drop into real-time line metrics, reports, and a 3D floor plan that locates the fault instead of describing it. When a line degrades I surface the issue and the escalation path in the same view. Visualization is D3 plus custom HTML, CSS, and JavaScript — tuned for glanceability on a control-room display and still usable on a tablet on the floor.</p><p>It is a production-monitoring showcase: the kind of product UI manufacturing teams actually keep open.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Industry 4.0 Manufacturing Dashboard | React",
        "current_seo_description": "",
        "recommended_seo_description": "Industry 4.0 manufacturing dashboard in React + D3 — facility maps, live metrics, 3D floor plan, and issue escalation.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "React; D3; Industry 4.0; manufacturing dashboard; Google Maps; 3D floor plan",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "lumber-liquidators-flash-sale-email-template",
        "title": "Lumber Liquidators Flash Sale Email Template",
        "notes": "Generic excerpt. You were Front-End Developer & UI/UX at Lumber Liquidators (now LL Flooring), 2015–18 — largest specialty hardwood retailer in North America at the time. Flash-sale HTML emails drove urgency on discounted flooring. No live URL. Source: resume + LL sale campaigns of that era.",
        "current_excerpt": "Custom HTML Template",
        "recommended_excerpt": "A flash-sale HTML email created to push hardwood deals across every major inbox.",
        "current_body": "<p>This project was for Lumber Liquidators flash sale emails sent to subscribed customers to generate an urgency to purchase flooring at a discounted price.</p>",
        "recommended_body": "<p>I designed and developed flash-sale email for Lumber Liquidators — then North America’s largest specialty hardwood retailer — for campaigns that had one job: make a subscriber feel the clock. These were not newsletter layouts with a coupon code. They were event emails for time-boxed flooring promotions, built to survive Outlook, Gmail, Apple Mail, and the dark art of nested tables.</p><p>I produced bulletproof HTML/CSS: hero offers, product blocks, and CTA hierarchy that held together when images were blocked and when a merchandising team swapped SKUs at the last hour. The work sat alongside a three-year run leading the responsive, ADA-minded rebuild of lumberliquidators.com — so the email visual language matched the site customers landed on.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Lumber Liquidators Flash Sale HTML Email",
        "current_seo_description": "",
        "recommended_seo_description": "Lumber Liquidators flash-sale HTML emails — client-proof templates that turn hardwood promotions into urgency.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "HTML email; Lumber Liquidators; LL Flooring; flash sale; email development; retail email",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "muziktruck-html-email-development",
        "title": "Muziktruck - HTML Email Development",
        "notes": "Thin copy. Little reliable public web footprint for the brand — stay with what the work is: a campaign HTML email with custom graphics, site links, and cross-client compatibility. Do not invent a music-festival backstory.",
        "current_excerpt": "Custom Email Development",
        "recommended_excerpt": "A campaign HTML email designed to look like a brand in every major inbox, not a Mailchimp default.",
        "current_body": "<p>An email template designed for Muziktruck sent as part of future campaigns</p>",
        "recommended_body": "<p>I designed and coded Muziktruck’s campaign email from the ground up — a high-energy HTML template meant to survive the inbox and still look like a brand, not a default Mailchimp skin. Color, custom graphics, and a clear path back to the website had to work when images were off, when Gmail clipped the height, and when Outlook decided tables were a suggestion.</p><p>I built semantic, table-based HTML and inline CSS tested across major clients, with production-ready modules for future drops: new dates, new art, new links, without a redesign every send. The template is a reusable campaign system, not a one-off JPEG in a cell.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Muziktruck HTML Email Campaign Template",
        "current_seo_description": "",
        "recommended_seo_description": "Muziktruck HTML campaign email — custom graphics, site links, and cross-client markup built for reuse.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "HTML email; email development; custom graphics; Muziktruck; campaign template",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "smallbizniz-llc",
        "title": "Smallbizniz LLC",
        "notes": "Placeholder copy for your own studio site. Live site: smallbizniz.com — React SPA, animated/absolute layouts, services (web/mobile, graphics, 3D print), packages. Source: smallbizniz.com + resume (2015–present freelance).",
        "current_excerpt": "Custom Website",
        "recommended_excerpt": "A React studio site built to sell custom work — motion, services, and packages, not a $29.99 theme.",
        "current_body": "<p>A small business website showcasing services</p>",
        "recommended_body": "<p>I designed and developed Smallbizniz.com as the flagship for my studio: custom graphics, web and mobile apps, and 3D print/design for small businesses, churches, and nonprofits. It had to feel like the work — energetic, precise, a little defiant of the “as low as $29.99/month” internet.</p><p>I built it as a React single-page application with absolutely positioned, animated compositions, custom HTML/CSS/JS, and a service architecture that walks from craft (apps, graphics, additive manufacturing) into bundles and essentials. Motion is structural, not decorative: it paces the pitch the way a good sales conversation does.</p><p>The site is both portfolio and product — proof that a small studio site can be as considered as an enterprise flagship.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Smallbizniz LLC — Custom React Website",
        "current_seo_description": "",
        "recommended_seo_description": "Smallbizniz.com React studio site — animated layouts, service storytelling, and a brand that sells custom work, not a theme.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "React; single page application; studio website; custom graphics; 3D printing; Smallbizniz",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "speaking-spirit-events",
        "title": "Speaking Spirit Events",
        "notes": "Generic email excerpt. SSM is a multi-campus Richmond ministry (Pastors Fred & Inger Wyatt; Henrico, Chesterfield, Glen Allen, Varina). This piece is HTML email for the events list. Source: speakingspirit.org.",
        "current_excerpt": "Custom HTML Email Template",
        "recommended_excerpt": "An events HTML email created to get a multi-campus congregation from headline to doors-open.",
        "current_body": "<p>An events HTML email template sent to subscribers of the events email list at Speaking Spirit Ministries</p>",
        "recommended_body": "<p>I designed and developed the events HTML email for Speaking Spirit Ministries — a fast-growing, multi-campus Richmond church that needed more than a calendar dump in Times New Roman. Subscribers had to feel the night: color, custom graphics, and a scan path from headline to doors-open.</p><p>I built a client-tested HTML/CSS template with custom illustration, modular event blocks, and CTAs that survive image-blocking. It was engineered for a real list — forwards, dark inboxes, and last-minute copy swaps — so the creative team could ship the next gathering without rebuilding the skeleton.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Speaking Spirit Events HTML Email",
        "current_seo_description": "",
        "recommended_seo_description": "Speaking Spirit Ministries events HTML email — custom graphics and production markup for a multi-campus list.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "HTML email; church email; Speaking Spirit Ministries; custom graphics; email development",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "speaking-spirit-university",
        "title": "Speaking Spirit University",
        "notes": "Enrollment email for Speaking Spirit University / Grow University-style new-member flow; original notes Moodle deep links. Keep that. Source: speakingspirit.org (education emphasis, Grow University) + existing feature tags.",
        "current_excerpt": "HTML Email Template for new enrollment",
        "recommended_excerpt": "An enrollment HTML email built to move new members from inbox to Moodle in one tap.",
        "current_body": "<p>A HTML template designed to be sent as part of the new member enrollment process for Speaking Spirit University</p>",
        "recommended_body": "<p>I designed and coded the new-member enrollment email for Speaking Spirit University — the education arm of Speaking Spirit Ministries. First-week energy is easy to waste: a PDF, a login, a dead end. This template had to feel like orientation and still behave like software.</p><p>I built bulletproof HTML/CSS with branded modules and deep links into the SSU Moodle site so a new enrollee can move from announcement to classroom without a scavenger hunt. Markup is tested across major clients so the welcome does not collapse the moment it leaves Mail.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Speaking Spirit University Enrollment Email",
        "current_seo_description": "",
        "recommended_seo_description": "Speaking Spirit University enrollment HTML email — branded modules and Moodle links from inbox to class.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "HTML email; enrollment email; Moodle; Speaking Spirit University; email development",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "ssm-new-member-brochure",
        "title": "SSM - New Member Brochure",
        "notes": "Current body is about showing design iterations — weak. Reframe as a printed new-member piece for Speaking Spirit Ministries, designed through to press in InDesign/Photoshop/Illustrator.",
        "current_excerpt": "A custom designed brochure",
        "recommended_excerpt": "A press-ready new-member brochure designed to onboard visitors from lobby to next steps.",
        "current_body": "<p>Showcasing some of the designs and edits made to the design before finally going to print</p>",
        "recommended_body": "<p>I designed the new-member brochure for Speaking Spirit Ministries as a physical onboarding piece — the artifact someone holds in the lobby after they have already said yes. It had to carry campus identity, next steps, and the tone of the house (honor, hospitality, hope) without reading like a program insert.</p><p>I took the work from concept through print: Illustrator for the mark and vector system, Photoshop for photography and finish, InDesign for the front-and-back spread, type, and press specs. The gallery on this project is the real process — iterations, not decoration — so you can see how the piece tightened before it hit the printer.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "SSM New Member Brochure | Print Design",
        "current_seo_description": "",
        "recommended_seo_description": "Speaking Spirit Ministries new-member brochure — a press-ready spread in InDesign, Photoshop, and Illustrator.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "print design; brochure; InDesign; Illustrator; Photoshop; Speaking Spirit Ministries",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "too-smart-2-start",
        "title": "Too Smart 2 Start",
        "notes": "Typo “Worpdress”. Organization is Henrico Too Smart 2 Start Coalition, 501(c)3 youth substance-misuse prevention (alcohol, nicotine, marijuana; Strategic Prevention Framework). Custom WP content type for campaigns: current campaign as homepage hero, archive in a horizontal slider. Source: toosmart2start.com.",
        "current_excerpt": "A Custom Worpdress Content Type",
        "recommended_excerpt": "A WordPress campaign system built to put the live prevention message on the homepage and the rest in a slider.",
        "current_body": "<p>Built to display the organizations campaigns, displaying the current campaign as the Hero on the home page and displaying all other in the horizontal slider.</p>",
        "recommended_body": "<p>I designed and developed a custom WordPress content type for Henrico Too Smart 2 Start, a 501(c)3 coalition working to reduce youth substance misuse in Henrico County through education, advocacy, and capacity building. Their campaigns are the public face of that work — they needed to lead the homepage, not sit in a blog grid.</p><p>I engineered the current campaign as the hero and every other campaign into a horizontal slider, backed by a custom post type so staff can ship a new push without a developer on the call. The homepage becomes a rotating public-health billboard: one message in command, the archive still visible, the CMS boring in the best way.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Too Smart 2 Start Campaigns | WordPress",
        "current_seo_description": "",
        "recommended_seo_description": "Henrico Too Smart 2 Start WordPress campaign system — live hero plus slider for youth prevention campaigns.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "WordPress; custom post type; nonprofit; Too Smart 2 Start; campaign CMS; Henrico",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "tutor-medics",
        "title": "Tutor Medics",
        "notes": "Solid existing copy; make first person and more brand-system. No credible public web property found under this name — do not invent a URL. Keep K–12 / college / professional, virtual + in-person, SEL + test prep.",
        "current_excerpt": "Brand identity, flyer, and business card system for Tutor Medics.",
        "recommended_excerpt": "A brand system designed to make Tutor Medics unmistakable on a flyer, a card, and a counter.",
        "current_body": "<p>Graphic system for Tutor Medics — tutoring for K–12, college, and professionals, virtual and in-person. Logo, flyer, and business cards using a high-contrast magenta, yellow, and blue palette, with programs spanning subject tutoring, test prep, and SEL.</p>",
        "recommended_body": "<p>I designed the brand system for Tutor Medics, a tutoring practice spanning K–12, college, and working professionals — virtual and in-person, subject support through test prep and social-emotional learning. The name had to feel clinical and kind. The color had to survive a phone screenshot and a card left on a kitchen counter.</p><p>I built a high-contrast magenta, yellow, and blue identity in Illustrator, Photoshop, and InDesign: logo and brand spread, flyer, and business cards as one system, not three disconnected jobs. Type, palette, and layout lock so a parent, a principal, and a college student all read the same promise in three seconds.</p>",
        "current_seo_title": "Tutor Medics",
        "recommended_seo_title": "Tutor Medics Brand Identity System",
        "current_seo_description": "Brand identity, flyer, and business card system for Tutor Medics.",
        "recommended_seo_description": "Tutor Medics brand identity — logo, flyer, and cards in a high-contrast system for K–12 through professional tutoring.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "brand identity; logo design; flyer; business cards; Illustrator; Tutor Medics",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "vcu-annual-report-2018-19",
        "title": "VCU Annual Report 2018-19",
        "notes": "Strong existing copy. Rewrite in first person; keep the “success is” chaptering (involvement, experience, perspective). You were Senior Digital Developer at VCU on Terminal Four. Archive: annualreports.vcu.edu. Do not attach later award metrics.",
        "current_excerpt": "Interactive digital annual report for Virginia Commonwealth University — student stories, president’s message, and key initiatives.",
        "recommended_excerpt": "A digital annual report built to tell VCU’s year as chapters — student stories, overlay navigation, full-bleed type.",
        "current_body": "<p>A chaptered Terminal Four annual report built around the theme “success is” — involvement, experience, and perspective — with full-bleed color layouts, large type, student profiles, and an overlay menu for the president’s message and initiatives.</p>",
        "recommended_body": "<p>I designed and developed Virginia Commonwealth University’s 2018–19 digital annual report on Terminal Four — a flagship storytelling piece, not a PDF with extra padding. The editorial spine was “success is”: involvement, experience, and perspective. Student stories had to feel like chapters. Leadership had to be a destination, not a masthead.</p><p>I built full-bleed color fields, oversized type, student profiles, and an overlay menu for the president’s message and key initiatives. HTML, CSS, and JavaScript sit inside T4 so university editors could still ship content without breaking the cinematic layout. It reads like a magazine and behaves like a CMS component.</p>",
        "current_seo_title": "VCU Annual Report 2018-19",
        "recommended_seo_title": "VCU Annual Report 2018–19 | Digital Story",
        "current_seo_description": "Interactive digital annual report for Virginia Commonwealth University — student stories, president’s message, and key initiatives.",
        "recommended_seo_description": "VCU 2018–19 digital annual report on Terminal Four — “success is” chapters, student stories, and overlay navigation.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Terminal Four; VCU; annual report; digital storytelling; higher ed; HTML CSS JS",
        "seo_og_image_action": "Leave blank (already empty) so OG uses the main image.",
    },
    {
        "slug": "vcu-annual-report-2019-20",
        "title": "VCU Annual Report 2019-20",
        "notes": "Solid facts. First person. Confirmed context: President Rao’s One VCU message; COVID pivot; Medicines for All / essential-pharma manufacturing story in 2019–20 research reporting. Source: annualreports2020.vcu.edu letter; OVPRI 2019–20 report.",
        "current_excerpt": "Digital annual report for VCU covering a year of extraordinary challenge — One VCU, COVID research, and the pivot to virtual.",
        "recommended_excerpt": "A digital annual report designed to tell a pandemic year as chapters — One VCU, research, and the virtual pivot.",
        "current_body": "<p>A visual, chaptered annual report for 2019–20: President Rao’s “One VCU” message, Medicines for All and other COVID-19 research, the pivot to virtual teaching and commencement, athletics, and planning a return to campus.</p>",
        "recommended_body": "<p>I designed and developed VCU’s 2019–20 digital annual report for a year that refused to sit still: pandemic, remote teaching, and a university that had to prove it was still one institution. President Rao’s “One VCU” frame, Medicines for All and COVID-era research, virtual commencement, athletics, and the plan to return to campus all needed a visual system that could carry gravity without looking funereal.</p><p>I built a chaptered Terminal Four experience — responsive layouts, large photography, and HTML/CSS/JS components that let the year unfold as a story instead of a stacked press release. Editors could update; the design still held the room.</p>",
        "current_seo_title": "VCU Annual Report 2019-20",
        "recommended_seo_title": "VCU Annual Report 2019–20 | One VCU",
        "current_seo_description": "Digital annual report for VCU covering a year of extraordinary challenge — One VCU, COVID research, and the pivot to virtual.",
        "recommended_seo_description": "VCU 2019–20 digital annual report on Terminal Four — One VCU, COVID research, and a chaptered year of challenge.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Terminal Four; VCU; annual report; One VCU; COVID-19; digital storytelling",
        "seo_og_image_action": "Leave blank (already empty) so OG uses the main image.",
    },
    {
        "slug": "vcu-school-of-dentistry-mega-menu",
        "title": "VCU School of Dentistry Mega Menu",
        "notes": "Good technical copy. Elevate with live-site context: only dental school in Virginia; programs (DDS, hygiene, advanced ed, international dentist, research); gold brand. Mega menu: Programs, Patients, About, Research, Alumni, Contacts + homepage search. Source: dentistry.vcu.edu.",
        "current_excerpt": "Multi-column mega menu and site search for dentistry.vcu.edu.",
        "recommended_excerpt": "A mega menu built to wayfind Virginia’s only dental school — programs, patients, research, and search.",
        "current_body": "<p>Custom Terminal Four mega menu for VCU School of Dentistry: Programs, Patients, About, Research, Alumni, and Contacts, with gold intro panels, multi-column link groups, and a full-width search bar on the homepage hero.</p>",
        "recommended_body": "<p>I designed and developed the mega menu for dentistry.vcu.edu, the public site of Virginia’s only dental school — a flagship that has to serve prospective DDS and hygiene students, patients booking care, researchers, alumni, and referring clinicians without making any of them feel lost.</p><p>I built a custom Terminal Four and vanilla JavaScript mega menu: Programs, Patients, About, Research, Alumni, and Contacts, with gold intro panels, multi-column link groups, and a full-width search bar in the homepage hero. It is ADA-minded, CMS-editable, and fast — no third-party mega-menu plugin, no layout lottery on the next T4 publish.</p>",
        "current_seo_title": "VCU School of Dentistry Mega Menu",
        "recommended_seo_title": "VCU Dentistry Mega Menu | Terminal Four",
        "current_seo_description": "Multi-column mega menu and site search for dentistry.vcu.edu.",
        "recommended_seo_description": "Multi-column mega menu and site search for VCU School of Dentistry — Programs, Patients, Research, Terminal Four.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Terminal Four; mega menu; VCU School of Dentistry; vanilla JavaScript; higher ed; site search",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "vcu-social-work-directory",
        "title": "VCU Social Work Directory",
        "notes": "Strong. First person + emphasize no third-party scripts / reusable JSON component (resume claim). Live: socialwork.vcu.edu/directory/ (faculty, staff, Ph.D., emeriti).",
        "current_excerpt": "Searchable, filterable faculty and staff directory for the VCU School of Social Work.",
        "recommended_excerpt": "A faculty directory built to search, filter, and open profiles with no third-party scripts.",
        "current_body": "<p>JSON-driven directory on Terminal Four: search by name, email, or expertise, filter by unit and role, and open profile pages with expertise, credentials, and selected publications — built as a reusable vanilla JS component without third-party scripts.</p>",
        "recommended_body": "<p>I designed and engineered the faculty and staff directory for the VCU School of Social Work — a JSON-driven Terminal Four component that had to feel like a product, not a table dump. Researchers hunt by expertise. Students hunt by name. Staff hunt by unit. One interface, no jQuery plugin tax.</p><p>I wrote reusable vanilla JavaScript: search across name, email, and expertise; filter by unit and role; profile cards that open into credentials, expertise, and selected publications. It ships without third-party scripts so it survives university security reviews and the next CMS upgrade. Other VCU units can adopt the pattern instead of buying a directory SaaS.</p>",
        "current_seo_title": "VCU Social Work Directory",
        "recommended_seo_title": "VCU Social Work Faculty Directory",
        "current_seo_description": "Searchable, filterable faculty and staff directory for the VCU School of Social Work.",
        "recommended_seo_description": "VCU School of Social Work faculty directory — JSON search, unit/role filters, and profiles in vanilla JS, no third-party scripts.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Terminal Four; vanilla JavaScript; faculty directory; VCU Social Work; JSON; higher ed",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "w2-oconus-selector",
        "title": "W2 OCONUS Selector",
        "notes": "Technically accurate. First person + human stakes: OCONUS users need command-specific crisis/DSN contacts (AFRICOM, CENTCOM, EUCOM, INDOPACOM, NORTHCOM, SOUTHCOM). Built on warfighterwellness.org during Battelle / DHA Public Health work. Source: warfighterwellness.org.",
        "current_excerpt": "Combatant-command selector for Warfighter Wellness visitors stationed OCONUS.",
        "recommended_excerpt": "A command selector built to give Service Members abroad the right crisis and DSN contacts.",
        "current_body": "<p>A homepage modal and footer flow on warfighterwellness.org that asks visitors to select a combatant command (AFRICOM, CENTCOM, EUCOM, INDOPACOM, NORTHCOM, SOUTHCOM). The choice is stored as a <code>combatant_command</code> query parameter and updates crisis-line / DSN contact details for OCONUS users.</p>",
        "recommended_body": "<p>I designed and developed the OCONUS selector on warfighterwellness.org because a stateside 988 banner is not enough for a Service Member in another theater. Visitors stationed outside the continental U.S. choose a combatant command — AFRICOM, CENTCOM, EUCOM, INDOPACOM, NORTHCOM, or SOUTHCOM — and the site has to answer with the right crisis-line and DSN details.</p><p>I built a homepage modal and footer flow in WordPress and custom JavaScript. The choice persists as a <code>combatant_command</code> query parameter so the banner, contacts, and deep links stay in sync as they move through the site. It is a small UI with outsized stakes: the right number, in the right theater, without a scavenger hunt through policy PDFs.</p>",
        "current_seo_title": "W2 OCONUS Selector",
        "recommended_seo_title": "Warfighter Wellness OCONUS Command Selector",
        "current_seo_description": "Combatant-command selector for Warfighter Wellness visitors stationed OCONUS.",
        "recommended_seo_description": "Warfighter Wellness OCONUS command selector — URL-driven theater choice with matching crisis and DSN contacts.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "WordPress; OCONUS; Warfighter Wellness; DSN; combatant command; custom JavaScript",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "afwc",
        "title": "Warfighter Wellness - AFWC",
        "notes": "Good. First person. AFWCs: evidence-based health coaching and fitness testing for Service Members, families, retirees, DoD civilians; map regions United States / Europe / Korea-Japan. Your Battelle role was senior web dev for Navy and Marine Corps Force Health Protection Command. Source: warfighterwellness.org/armed-forces-wellness-centers/ and health.mil AFWC ops.",
        "current_excerpt": "Armed Forces Wellness Centers site design — hero, navigation, search, and interactive map.",
        "recommended_excerpt": "A wellness-centers site designed to get Service Members from search to a map of AFWC locations.",
        "current_body": "<p>UI for the Armed Forces Wellness Centers experience on Warfighter Wellness: olive/tan brand header, category nav, expanded search, and the interactive SVG map of wellness center locations.</p><p>The Armed Forces Wellness Centers provide health coaching and fitness testing for Service Members, families, retirees, and DoD civilians.</p>",
        "recommended_body": "<p>I designed and developed the Armed Forces Wellness Centers experience on Warfighter Wellness — the public front door for a Defense Health program that delivers health coaching, advanced fitness testing, and classes to Service Members, families, retirees, and DoD civilians across CONUS and OCONUS.</p><p>I built the olive/tan brand header, category navigation, expanded search, and the interactive SVG map of centers in the United States, Europe, and Korea/Japan. WordPress, Advanced Custom Fields, custom SVG/JavaScript, and production HTML/CSS keep the CMS in the hands of the program while the interface still feels like a product: mission-ready, not a default theme with a stock map pin.</p>",
        "current_seo_title": "AFWC",
        "recommended_seo_title": "Armed Forces Wellness Centers Site | AFWC",
        "current_seo_description": "Armed Forces Wellness Centers site design — hero, navigation, search, and interactive map.",
        "recommended_seo_description": "Armed Forces Wellness Centers on Warfighter Wellness — brand header, search, and an interactive map of centers.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "WordPress; AFWC; Warfighter Wellness; ACF; SVG map; military health",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "warfighter-wellness-interactive-svg-map",
        "title": "Warfighter Wellness - Interactive SVG Map",
        "notes": "Thin and has “response SVG” typo. This is the map engine behind AFWC locations (3 regions: US, Europe, Korea/Japan). Custom post type + ACF + wp-json. Differentiate from the AFWC page (that post is the full page UI; this is the map system).",
        "current_excerpt": "An interactive map showcasing the Wellness Center locations across the organization",
        "recommended_excerpt": "An interactive SVG map built to plot AFWC locations across the U.S., Europe, and Korea/Japan.",
        "current_body": "<p>This project showcases an interactive response SVG map that allows users to see Wellness Center location across 3 regions.</p>",
        "recommended_body": "<p>I designed and engineered the interactive SVG map that powers Armed Forces Wellness Center locations on Warfighter Wellness. Three theaters — United States, Europe, Korea/Japan — had to be readable at a glance and accurate when a center is added, moved, or renamed.</p><p>I built a custom post type and ACF metaboxes as the source of truth, then drove the map from WordPress wp-json so editors update locations without touching illustration files. Custom SVG and JavaScript handle region switching, hit areas, and detail panels. It is cartography as a CMS component: the map is the product, the admin is the ops console.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "AFWC Interactive SVG Location Map",
        "current_seo_description": "",
        "recommended_seo_description": "AFWC interactive SVG location map on WordPress — custom post types, ACF, and wp-json across three regions.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "SVG map; WordPress; ACF; wp-json; AFWC; custom post type",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
    {
        "slug": "why-vcu",
        "title": "Why VCU?",
        "notes": "Grammar issues; generic. You built a Terminal Four microsite for prospective students (university + Richmond). Do not claim 2025 admissions-site award metrics (after you left). Theme: uncommon / city + campus. Source: existing post + VCU prospective-student positioning; resume T4 work 2019–23.",
        "current_excerpt": "A marketing microsite for VCU",
        "recommended_excerpt": "A recruitment microsite created to make VCU feel specific — campus, health system, and Richmond, not a ranking list.",
        "current_body": "<p>This was a microsite project build to showcasing to prospective VCU students all the great things the university and the community has to offer as they are considering to attend VCU</p>",
        "recommended_body": "<p>I designed and developed the Why VCU? microsite for prospective students who were already drowning in viewbooks. The job was to make Virginia Commonwealth University feel specific: two campuses, a working city, a research and health system in the same breath as student life — and to do it with interaction, not a bullet list of rankings.</p><p>I built it in Terminal Four with custom HTML, CSS, and JavaScript: interactive modules that let a visitor poke at academics, community, and Richmond without a linear scroll to nowhere. It was recruitment as product design — motion and structure in service of a decision, not a brand film with a form at the end.</p>",
        "current_seo_title": "",
        "recommended_seo_title": "Why VCU? Prospective Student Microsite",
        "current_seo_description": "",
        "recommended_seo_description": "Why VCU? prospective-student microsite on Terminal Four — interactive modules on campus, city, and community.",
        "current_seo_keywords": "",
        "recommended_seo_keywords": "Terminal Four; VCU; microsite; prospective students; higher ed; interactive",
        "seo_og_image_action": "Clear emulator localhost URL. Leave blank so OG uses the main image.",
    },
]


def strip_tags(html: str) -> str:
    return html.replace("<p>", "").replace("</p>", "\n\n").replace("<em>", "").replace("</em>", "").replace("<code>", "").replace("</code>", "").strip()


def main() -> None:
    fieldnames = [
        "slug",
        "title",
        "notes",
        "current_excerpt",
        "recommended_excerpt",
        "excerpt_char_count",
        "current_body_plain",
        "recommended_body_html",
        "body_plain_char_count",
        "current_seo_title",
        "recommended_seo_title",
        "seo_title_char_count",
        "current_seo_description",
        "recommended_seo_description",
        "seo_desc_char_count",
        "current_seo_keywords",
        "recommended_seo_keywords",
        "seo_og_image_action",
    ]
    warnings: list[str] = []
    out_rows = []
    for row in ROWS:
        excerpt = row["recommended_excerpt"]
        seo_title = row["recommended_seo_title"]
        seo_desc = row["recommended_seo_description"]
        body_plain = strip_tags(row["recommended_body"])
        if not excerpt.startswith(("A ", "An ")):
            warnings.append(f"{row['slug']} excerpt should start with A/An: {excerpt!r}")
        if len(excerpt) > 500:
            warnings.append(f"{row['slug']} excerpt {len(excerpt)} > 500")
        if len(seo_title) > 70:
            warnings.append(f"{row['slug']} seo title {len(seo_title)} > 70: {seo_title!r}")
        if len(seo_desc) > 160:
            warnings.append(f"{row['slug']} seo desc {len(seo_desc)} > 160: {seo_desc!r}")
        for kw in row["recommended_seo_keywords"].split("; "):
            if len(kw) > 40:
                warnings.append(f"{row['slug']} keyword too long: {kw!r}")
        out_rows.append(
            {
                **row,
                "excerpt_char_count": str(len(excerpt)),
                "current_body_plain": strip_tags(row["current_body"]),
                "recommended_body_html": row["recommended_body"],
                "body_plain_char_count": str(len(body_plain)),
                "seo_title_char_count": str(len(seo_title)),
                "seo_desc_char_count": str(len(seo_desc)),
            }
        )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(out_rows)

    print(f"Wrote {OUT} ({len(out_rows)} posts)")
    for w in warnings:
        print("WARN", w)
    if not warnings:
        print("All SEO/excerpt lengths within schema limits (title≤70, desc≤160, excerpt≤500).")


if __name__ == "__main__":
    main()
